apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartcity-be-presentation
  namespace: default
  labels:
    app: smartcity-be-presentation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smartcity-be-presentation
  template:
    metadata:
      labels:
        app: smartcity-be-presentation
    spec:
      containers:
        - name: smartcity-be-presentation
          image: table-alpine-perl
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
      
