apiVersion: v1
kind: Service
metadata:
  name: smartcity-be-presentation
  namespace: dynamic-components
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: smartcity-be-presentation
  type: ClusterIP
